_common/shippable/Adapter.js
tests/core_account_tests.js

https://github.com/Shippable/bvt-v2/issues/3
set timeout for mocha
retry on api timeout

bvt v2 set mocha timeout and retry on api timeout

---

_common/setupTests.js
doCleanup.js
local.env.template

https://github.com/Shippable/bvt-v2/issues/7

fix environment variable for JOB_STATE

---

package.json
tests/core_account_tests.js

login - should finish syncing account

---

_common/setupTests.js
tests/core_account_tests.js

login - check projects and subscriptions created

---

_common/setupTests.js
_common/shippable/Adapter.js
local.env.template
local.sh
package.json
test.sh
tests/core/GHC-ORG-PRI-ADM.js

test to enable a private project for github owner

---

doCleanup.js

add project cleanup logic

---

_common/shippable/Adapter.js
tests/core/GHC-ORG-PRI-ADM.js

can sync private project

---

tests/core/GHC-ORG-PRI-ADM.js

add tests to pause and resume a private project

---

README.md
_common/setupTests.js
local.env.template
package.json
tests/core_login/ACC-GHC-MEM-IND.js
tests/core_login/ACCT-GHC-ADM-IND.js

https://github.com/Shippable/pm/issues/8506

adds login tests for github member

---

_common/setupTests.js
local.env.template
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-MEM.js
tests/core_login/ACC-GHC-COL-IND.js

adds tests to enable, sync, pause and resume a private project

---

tests/core/GHC-ORG-PRI-COL.js

use suAdapter to delete instead of collab

---

_common/setupTests.js
local.env.template
tests/core_login/ACC-GHC-COL-IND.js
tests/core_login/ACCT-GHC-MEM-IND.js

add tests for member login

---

README.md
_common/setupTests.js
tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js

add check if project is created before saving it to nconf

add tests for member project enable, sync, pause and resume

---

tests/core_login/ACC-GHC-COL-IND.js
tests/core_login/ACCT-GHC-ADM-IND.js
tests/core_login/ACCT-GHC-MEM-IND.js

add role field to resources json

---

tests/core_login/ACC-GHC-COL-IND.js

Fix apiToken not getting populated in resources json for collab

---

_common/setupTests.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core_login/ACCT-GHC-ADM-IND.js

ghcOwnerAdapter should be ghcAdminAdapter to be consistent with role name and test case name

rename ghcOwnerAdapter to make it consistent with role names

---

.eslintrc.js
tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core_login/ACCT-GHC-MEM-IND.js

add tests for public user project enable, sync, pause and resume

---

_common/setupTests.js
tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-UNA.js

also, fixes RC crashing due to enable project by service user
collab uses org project instead of individual project now

use admin adapter and enable project before member tests

---

doCleanup.js
local.sh
package.json
test.sh
testRunner.js
tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-UNA.js

`testRunner.js` script captures output on stdout. this will be used to create github issues based on assertions and errors.

change the testRunner to capture assertion error 

---

tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js

adds tests for triggering, cancelling manual builds, viewing logs

---

testRunner.js
tests/core/GHC-IND-PRI-MEM.js
tests/core_login/ACC-GHC-COL-IND.js

add tests for member to trigger manual builds and view logs

---

tests/core/GHC-ORG-PRI-UNA.js

https://github.com/Shippable/bvt-v2/issues

adds tests for public user triggering builds

---

_common/setupTests.js
tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js

add download log tests for member and collab

---

_common/setupTests.js
tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PUB-COL.js
tests/core_login/ACC-GHC-COL-IND.js
tests/core_login/ACCT-GHC-ADM-IND.js
tests/core_login/ACCT-GHC-MEM-IND.js

add tests for public project for collab

---

tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-IND-PUB-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PUB-COL.js

add test case for reset cache

---

tests/core/GHC-IND-PUB-MEM.js

Fix status for PUB MEM

---

tests/core/GHC-ORG-PUB-ADM.js

add tests for public project for admin

---

_common/github/Adapter.js
_common/setupTests.js
tests/core/GHC-ORG-PRI-PRE-ADM.js

add GHC-ORG-PRI-PRE-ADM

---

tests/core/GHC-ORG-PRI-PRE-COL.js

add GHC-ORG-PRI-PRE-COL

---

.eslintrc.js
_common/setupTests.js
_common/shippable/Adapter.js
doCleanup.js
testRunner.js
tests/core/GHC-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-ADM.js
tests/core_login/ACCT-GHC-ADM-IND.js
tests/core_login/ACCT-GHC-COL-IND.js
tests/core_login/ACCT-GHC-MEM-IND.js

adds test for sync Repo for admin

---

tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

adds tests for soft and hard delete for admin + tests for collab

---

tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

add exponential backoff for rsync to finish

---

tests/core/RES-ORG-PUB-ADM.js

Add RES-ORG-PUB-ADM trigger job and cancel job testcases

---

tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

also adds backoff until builds are created
tested locally 

add tests to trigger job for collab

---

tests/core/RES-ORG-PRI-ADM.js
tests/core/RES-ORG-PRI-COL.js

adds test for collab and admin for private project

---

tests/core_login/ACCT-GHC-COL-IND.js

remove if condition which is not required from ACCT-GHC-COL-IND

---

_common/setupTests.js
tests/core_login/ACCT-GHC-MEM-IND.js

adds tests for member projectAccount role

---

_common/setupTests.js
tests/core/RES-IND-PRI-MEM.js

resources tests for github individual member for private project

---

tests/core/RES-IND-PRI-MEM.js
tests/core/RES-ORG-PRI-ADM.js
tests/core/RES-ORG-PRI-COL.js
tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

adds debug log to check why statusCode is not defined

---

tests/core/GHC-ORG-PRI-UNA-2.js

rename tests to include unauthenitcated users signed up on shippable

---

tests/core/GHC-ORG-PRI-UNO.js

use UNO for unauthorized users

---

tests/core/RES-IND-PRI-MEM.js
tests/core/RES-ORG-PRI-ADM.js
tests/core/RES-ORG-PRI-COL.js
tests/core/RES-ORG-PRI-UNA.js
tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

	adds tests for resources for UNA users + cleanup logic for builds

---

tests/core/RES-IND-PRI-MEM.js
tests/core/RES-ORG-PRI-ADM.js
tests/core/RES-ORG-PRI-COL.js
tests/core/RES-ORG-PRI-UNA.js
tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

wait until build is in processing state

---

tests/core/RES-IND-PRI-MEM.js
tests/core/RES-ORG-PRI-ADM.js
tests/core/RES-ORG-PRI-COL.js
tests/core/RES-ORG-PRI-UNA.js
tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

remove logs after debugging

---

tests/core/RES-ORG-PRI-ADM.js
tests/core/RES-ORG-PUB-ADM.js

wait before hard deleting resources for admin

---

tests/core/RES-IND-PRI-MEM.js
tests/core/RES-ORG-PRI-ADM.js
tests/core/RES-ORG-PRI-COL.js
tests/core/RES-ORG-PRI-UNA.js
tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

wait before hard deleting resources for all users

---

tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PRI-UNO.js
tests/core/GHC-ORG-PUB-ADM.js
tests/core/GHC-ORG-PUB-COL.js

trigger build with branchName

---

tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-PRE-ADM.js
tests/core/GHC-ORG-PRI-PRE-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PRI-UNO.js
tests/core/GHC-ORG-PUB-ADM.js
tests/core/GHC-ORG-PUB-COL.js

adds better logging if cleanup fails

---

tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PUB-ADM.js
tests/core/GHC-ORG-PUB-COL.js

adds tests to rerun builds

---

scripts/create_tag.sh
tests/core/GHC-ORG-PRI-TAG-ADM.js

Add test for Github organization tag build for private project by admin

---

scripts/create_commit.sh
scripts/create_tag.sh

remove git clone after pushing tag and commit

---

tests/core/ACCT-GHC-ADM-ORG.js
tests/core_login/ACCT-GHC-COL-IND.js

test to check if member of org is a collaborator and org admin is sub admin

---

tests/core/GHC-ORG-PRI-REE-ADM.js

remove create_tag script from create release test case

---

tests/core/GHC-ORG-PUB-PRE-ADM.js

add tests for admin pull request for public project

---

tests/core/GHC-ORG-PUB-PRE-ADM.js

fix public project name

---

tests/core/GHC-ORG-PUB-PRE-COL.js

adds tests for public project pull request for collab

---

scripts/create_commit.sh
scripts/create_tag.sh
tests/core/GHC-ORG-PRI-COM-ADM.js
tests/core/GHC-ORG-PUB-COM-ADM.js

Add tests for Github org public project commit by admin

---

_common/shippable/Adapter.js

https://github.com/Shippable/bvt-v2/issues/77

adds debug log to check why bvt fails to trigger new build request

---

scripts/create_tag.sh
tests/core/GHC-ORG-PRI-TAG-ADM.js
tests/core/GHC-ORG-PUB-TAG-ADM.js

Add tests for Github org public project tag build by admin

---

tests/core/skippable/GHC-ORG-PRI-COM-ADM.js
tests/core/skippable/GHC-ORG-PRI-PRE-ADM.js
tests/core/skippable/GHC-ORG-PRI-PRE-COL.js
tests/core/skippable/GHC-ORG-PRI-REE-ADM.js
tests/core/skippable/GHC-ORG-PRI-TAG-ADM.js
tests/core/skippable/GHC-ORG-PUB-COM-ADM.js
tests/core/skippable/GHC-ORG-PUB-PRE-ADM.js
tests/core/skippable/GHC-ORG-PUB-PRE-COL.js
tests/core/skippable/GHC-ORG-PUB-TAG-ADM.js

https://github.com/Shippable/pm/issues/8506

fix import paths for tests

---

tests/core/skippable/GHC-ORG-PUB-PRE-ADM.js

fix import paths for admin public pre

---

_common/setupTests.js
tests/core/skippable/GHC-ORG-PUB-REE-ADM.js

Add tests for  Github org public project release build by admin

---

tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PRI-UNO.js
tests/core/GHC-ORG-PUB-ADM.js
tests/core/GHC-ORG-PUB-COL.js

https://github.com/Shippable/bvt-v2/issues/79

improve cleanup logic for project deletion

---

_common/setupTests.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/skippable/GHC-ORG-PRI-COM-ADM.js
tests/core/skippable/GHC-ORG-PRI-PRE-ADM.js
tests/core/skippable/GHC-ORG-PRI-PRE-COL.js
tests/core/skippable/GHC-ORG-PRI-REE-ADM.js
tests/core/skippable/GHC-ORG-PRI-TAG-ADM.js
tests/core/skippable/GHC-ORG-PRI-TAG-COL.js
tests/core/skippable/GHC-ORG-PUB-REE-ADM.js

Add tests for Github org private project tag build by collaborator

---

tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PUB-ADM.js

Fix case when projectId not found test getting stuck

---

tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PRI-UNO.js
tests/core/GHC-ORG-PUB-COL.js
tests/core/skippable/GHC-ORG-PRI-COM-ADM.js
tests/core/skippable/GHC-ORG-PRI-COM-COL.js
tests/core/skippable/GHC-ORG-PRI-PRE-ADM.js
tests/core/skippable/GHC-ORG-PRI-PRE-COL.js
tests/core/skippable/GHC-ORG-PRI-REE-ADM.js
tests/core/skippable/GHC-ORG-PRI-REE-COL.js
tests/core/skippable/GHC-ORG-PRI-TAG-ADM.js
tests/core/skippable/GHC-ORG-PRI-TAG-COL.js
tests/core/skippable/GHC-ORG-PUB-COM-ADM.js
tests/core/skippable/GHC-ORG-PUB-COM-COL.js
tests/core/skippable/GHC-ORG-PUB-PRE-ADM.js
tests/core/skippable/GHC-ORG-PUB-PRE-COL.js
tests/core/skippable/GHC-ORG-PUB-REE-ADM.js
tests/core/skippable/GHC-ORG-PUB-REE-COL.js
tests/core/skippable/GHC-ORG-PUB-TAG-ADM.js
tests/core/skippable/GHC-ORG-PUB-TAG-COL.js

Add done callback to add after blocks to prevent test getting stuck

---

scripts/create_commit.sh
tests/core/skippable/GHC-ORG-PRI-COM-ADM.js

test commit to non-master branch

---

scripts/create_commit.sh

tests are failing because we are pusihng without doing a `git checkout`

fix bvt - checkout to non master branch before commit

---

_common/setupTests.js
tests/core/skippable/RunCI.16.js

adds test to check common services and environment variables for u14

---

_common/setupTests.js
tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PRI-UNO.js
tests/core/GHC-ORG-PUB-ADM.js
tests/core/GHC-ORG-PUB-COL.js
tests/core/RES-IND-PRI-MEM.js
tests/core/RES-ORG-PRI-ADM.js
tests/core/RES-ORG-PRI-COL.js
tests/core/RES-ORG-PRI-UNA.js
tests/core/RES-ORG-PUB-ADM.js
tests/core/RES-ORG-PUB-COL.js

https://github.com/Shippable/bvt-v2/issues/75

Add delay after cancel build to resource testcases, permission testcases

---

dummy_commit.txt
tests/core/skippable/GHC-ORG-PRI-COM-ADM.js
tests/core/skippable/GHC-ORG-PRI-COM-COL.js
tests/core/skippable/GHC-ORG-PRI-PRE-ADM.js
tests/core/skippable/GHC-ORG-PRI-PRE-COL.js
tests/core/skippable/GHC-ORG-PRI-REE-ADM.js
tests/core/skippable/GHC-ORG-PRI-REE-COL.js
tests/core/skippable/GHC-ORG-PRI-TAG-ADM.js
tests/core/skippable/GHC-ORG-PRI-TAG-COL.js
tests/core/skippable/GHC-ORG-PUB-COM-ADM.js
tests/core/skippable/GHC-ORG-PUB-COM-COL.js
tests/core/skippable/GHC-ORG-PUB-PRE-ADM.js
tests/core/skippable/GHC-ORG-PUB-PRE-COL.js
tests/core/skippable/GHC-ORG-PUB-REE-ADM.js
tests/core/skippable/GHC-ORG-PUB-REE-COL.js
tests/core/skippable/GHC-ORG-PUB-TAG-ADM.js
tests/core/skippable/GHC-ORG-PUB-TAG-COL.js

https://github.com/Shippable/bvt-v2/issues/75

add delay after cancelling build to all skippable testcases

---

_common/setupTests.js
tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PRI-UNO.js
tests/core/GHC-ORG-PUB-ADM.js
tests/core/GHC-ORG-PUB-COL.js
tests/core/skippable/GHC-ORG-PRI-COM-ADM.js
tests/core/skippable/GHC-ORG-PRI-COM-COL.js
tests/core/skippable/GHC-ORG-PRI-PRE-ADM.js
tests/core/skippable/GHC-ORG-PRI-PRE-COL.js
tests/core/skippable/GHC-ORG-PRI-REE-ADM.js
tests/core/skippable/GHC-ORG-PRI-REE-COL.js
tests/core/skippable/GHC-ORG-PRI-TAG-ADM.js
tests/core/skippable/GHC-ORG-PRI-TAG-COL.js
tests/core/skippable/GHC-ORG-PUB-COM-ADM.js
tests/core/skippable/GHC-ORG-PUB-COM-COL.js
tests/core/skippable/GHC-ORG-PUB-PRE-ADM.js
tests/core/skippable/GHC-ORG-PUB-PRE-COL.js
tests/core/skippable/GHC-ORG-PUB-REE-ADM.js
tests/core/skippable/GHC-ORG-PUB-REE-COL.js
tests/core/skippable/GHC-ORG-PUB-TAG-ADM.js
tests/core/skippable/GHC-ORG-PUB-TAG-COL.js
tests/core/skippable/RunCI.16.js
tests/core/skippable/RunCI.17.js

https://github.com/Shippable/bvt-v2/issues/75

add exp backoff before delete project instead of sleep

---

scripts/create_commit.sh

https://github.com/Shippable/bvt-v2/issues/100

create a new commit instead of ammending

---

tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PRI-UNO.js
tests/core/GHC-ORG-PUB-ADM.js
tests/core/GHC-ORG-PUB-COL.js

Need more info to debug
```
1) GHC-ORG-PRI-UNO - TestSuite for Github Org, public project for Unauthorized Users 5. CANNOT trigger manual builds:
Error: Cannot trigger manual build for project id: 58ad68ef221d740500f94315, err: 409, [object Object]
at tests/core/GHC-ORG-PRI-UNO.js:193:33
at _common/shippable/Adapter.js:1154:9
at node_modules/async/dist/async.js:3838:9
at node_modules/async/dist/async.js:421:16
at replenish (node_modules/async/dist/async.js:941:25)
at iterateeCallback (node_modules/async/dist/async.js:931:17)
at node_modules/async/dist/async.js:906:16
at node_modules/async/dist/async.js:3835:13
at _parseBody (_common/shippable/Adapter.js:1277:10)
```

add more debugging messages

---

tests/core/GHC-ORG-PUB-ADM.js

https://app.shippable.com/github/Shippable/jobs/bvt-v2/builds/59e5a14ddcff93070055a83d/console

print more debug info

---

tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js

https://app.shippable.com/github/Shippable/jobs/bvt-v2/builds/59e5dc4b6a6aec070098561d/console

adds debug logs

---

tests/core/GHC-ORG-PRI-ADM.js
tests/core/GHC-ORG-PRI-COL.js
tests/core/GHC-ORG-PUB-COL.js

https://app.shippable.com/github/Shippable/jobs/bvt-v2/builds/59e5efc60211c206004952e9/

add debug logs

---

tests/core/GHC-IND-PRI-MEM.js
tests/core/GHC-ORG-PRI-UNA.js
tests/core/GHC-ORG-PRI-UNO.js

https://app.shippable.com/github/Shippable/jobs/bvt-v2/builds/59e5fae506231107000d5fd1/console

add debug logs for custom builds
